spring:
  application:
    name: item-service
  cloud:
    config:
     override-none: true 
  rabbitmq:
    host: 192.168.0.122
    port: 15672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka, http://127.0.0.1:2002/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh