spring:
  application:
    name: item-service
  cloud:
    config:
     override-none: true 
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka, http://127.0.0.1:2002/eureka